// Mock data for Recepción de Mercancía
// Includes actas, detalle de actas y centros de distribución

export const centrosDistribucionMock = [
  {
    Id: 1,
    Nombre: 'Centro Principal',
    Direccion: 'Av. Industrial 123',
    IdCentroPoblado: 11_001,
  },
  {
    Id: 2,
    Nombre: 'Bodega Norte',
    Direccion: 'Calle 45 #18-20',
    IdCentroPoblado: 11_002,
  },
]

export const actasMock = [
  {
    IdActa: 101,
    NroActa: 'ACT-001',
    IdProveedor: 501,
    ProveedorNombre: 'Proveedor Andino S.A.',
    Observaciones: 'Orden de compra OC-2024-001',
    PrefijoFacturaRecibida: 'FAC',
    NumeroFacturaRecibida: '8901',
    FechaFacturaRecibida: '2024-03-20',
    FechaActa: '2024-03-22',
    EstadoActa: 'Pendiente',
    IdUsuario: 10,
    CentroDistribucion: centrosDistribucionMock[0],
    Detalles: [
      {
        IdProducto: 9001,
        NombreProducto: 'Guantes de Nitrilo',
        IdLote: 'LOT-889',
        CantidadFacturada: 500,
        CantidadRecibida: 480,
        CantidadMuestra: 5,
        Aceptado: true,
        ObservacionesProducto: '5 cajas con abolladuras menores',
      },
      {
        IdProducto: 9002,
        NombreProducto: 'Jeringas 5ml',
        IdLote: 'LOT-223',
        CantidadFacturada: 1000,
        CantidadRecibida: 1000,
        CantidadMuestra: 10,
        Aceptado: true,
        ObservacionesProducto: 'Sin novedades',
      },
      {
        IdProducto: 9002,
        NombreProducto: 'Jeringas 5ml',
        IdLote: 'LOT-223',
        CantidadFacturada: 1000,
        CantidadRecibida: 1000,
        CantidadMuestra: 10,
        Aceptado: true,
        ObservacionesProducto: 'Sin novedades',
      },
    ],
  },
  {
    IdActa: 102,
    NroActa: 'ACT-002',
    IdProveedor: 502,
    ProveedorNombre: 'MedSupply SAS',
    Observaciones: 'OC-2024-014',
    PrefijoFacturaRecibida: 'FS',
    NumeroFacturaRecibida: '4567',
    FechaFacturaRecibida: '2024-03-25',
    FechaActa: '2024-03-26',
    EstadoActa: 'Cerrada',
    IdUsuario: 12,
    CentroDistribucion: centrosDistribucionMock[1],
    Detalles: [
      {
        IdProducto: 9010,
        NombreProducto: 'Mascarillas KN95',
        IdLote: 'KN-001',
        CantidadFacturada: 300,
        CantidadRecibida: 300,
        CantidadMuestra: 5,
        Aceptado: true,
        ObservacionesProducto: 'Empaque en buen estado',
      },
      {
        IdProducto: 9011,
        NombreProducto: 'Batas Desechables',
        IdLote: 'BT-777',
        CantidadFacturada: 200,
        CantidadRecibida: 190,
        CantidadMuestra: 3,
        Aceptado: false,
        ObservacionesProducto: '10 unidades con manchas',
      },
    ],
  },
  {
    IdActa: 103,
    NroActa: 'ACT-003',
    IdProveedor: 503,
    ProveedorNombre: 'Hospitalar LTDA',
    Observaciones: 'OC-2024-025',
    PrefijoFacturaRecibida: 'HF',
    NumeroFacturaRecibida: '3344',
    FechaFacturaRecibida: '2024-04-01',
    FechaActa: '2024-04-02',
    EstadoActa: 'Borrador',
    IdUsuario: 9,
    CentroDistribucion: centrosDistribucionMock[0],
    Detalles: [
      {
        IdProducto: 9020,
        NombreProducto: 'Solución Salina 0.9% 500ml',
        IdLote: 'SS-550',
        CantidadFacturada: 200,
        CantidadRecibida: 0,
        CantidadMuestra: 0,
        Aceptado: false,
        ObservacionesProducto: 'A la espera de recepción física',
      },
    ],
  },
]
